### ISSUE TITLE
Editor and buttons not loading for me

### ISSUE THREAD

**Issue by amviro** [Vinelab/laravel-editor#9]
Editor is not loading properly for me (screenshot attached).
Css and js files are properly added and loading though.

![capture](https://cloud.githubusercontent.com/assets/5769361/6940797/f77e3874-d89b-11e4-8c3d-b30e4d6df58e.JPG)

**Comment by Mulkave** [comment]
@almamundinajpuri  Can u please open the browser console and send the errors you have there.

**Comment by amviro** [comment]
Hi Mulkave,
I've getting this error in console

```
TypeError: $(...).markdown is not a function
callback: function(e){
```

![capture](https://cloud.githubusercontent.com/assets/5769361/7571686/154f9e74-f83b-11e4-8fd1-18f58582b43c.JPG)

**Comment by Mulkave** [comment]
Hi @almamundinajpuri, that's probably because the markdown script is missing from the page. Following the instructions in [the docs](https://github.com/Vinelab/laravel-editor#dependencies) all of the dependencies are required, jQuery and Bootstrap.

After making sure these are in the page, make sure you have run `php artisan vendor:publish` so that it publishes the required resource files for the package which in turn should say the following

```
Copied Directory [/vendor/vinelab/laravel-editor/src/views] To [/resources/views/vendor/laravel-editor]
Copied Directory [/vendor/vinelab/laravel-editor/public] To [/public/vendor/laravel-editor]
```

After that everything should be working. Please let me know if you face any difficulties in the mentioned steps.

**Comment by amviro** [comment]
Hi @Mulkave,
Thank you for the quick reply.
"bootstrap-markdown.js" file was not loading for me.
It works fine now.

Regards
